name: 'Deploy with DReAM CLI'
description: 'Deploy resources with DReAM CLI up command'
inputs:
  workspace:
    description: 'DReAM workspace to deploy to'
    required: true
  private-key:
    description: 'DReAM workspace private key'
    required: true
  production:
    description: 'Enable production flag, this will remove dev dependencies (default true)'
    default: 'true'
  flag:
    description: 'Flag to pass to dream up command'
    required: false
runs:
  using: "composite"
  steps:
    - name: Deploy
      env:
        PRIVATE_KEY: ${{ inputs.private-key }}
        WORKSPACE: ${{ inputs.workspace }}
        FLAG: ${{ inputs.production == 'true' && '--production' || '' }}
        FLAG2: ${{ inputs.flag || '' }}
      run: |
        echo "${PRIVATE_KEY}" > ~/dream-private-${WORKSPACE}.pem
        dream set-private-key -w ${WORKSPACE} ~/dream-private-${WORKSPACE}.pem
        dream init -w ${WORKSPACE}
        dream up ${FLAG} ${FLAG2}
      shell: "bash"
